name: Build RedSun Multi-Arch
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC (${{ matrix.arch }})
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Compile RedSun
        # Added /D UNICODE and /D _UNICODE to fix the wchar_t to LPCSTR conversion errors
        run: cl.exe /EHsc /std:c++17 /D UNICODE /D _UNICODE RedSun.cpp /out:RedSun_${{ matrix.arch }}.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RedSun-Binaries-${{ matrix.arch }}
          path: RedSun_${{ matrix.arch }}.exe