name: Build RedSun Multi-Arch
on:
  push:
  workflow_dispatch: # This allows you to trigger the build manually from the "Actions" tab

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated from v3 to v4

      - name: Setup MSVC (${{ matrix.arch }})
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Compile RedSun
        # This compiles the RedSun PoC using the official Microsoft compiler
        run: cl.exe /EHsc /std:c++17 RedSun.cpp /out:RedSun_${{ matrix.arch }}.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # Updated from v3 to v4 to fix the error
        with:
          name: RedSun-Binaries-${{ matrix.arch }}
          path: RedSun_${{ matrix.arch }}.exe